vich_uploader:
    db_driver: orm

    mappings:
       post_image:
            uri_prefix: /images/books
            upload_destination: '%kernel.project_dir%/public/images/books'
            # namer: Vich\UploaderBundle\Naming\OrignameNamer
            namer: Vich\UploaderBundle\Naming\UniqidNamer